FROM ubuntu:22.04

RUN apt update -y && \
    apt install -y \
    libaio1
    
WORKDIR /opt/oracle

COPY oracle .

RUN sh -c "echo /opt/oracle/instantclient_23_7 > \
    /etc/ld.so.conf.d/oracle-instantclient.conf" && \
    ldconfig

ENV ORACLE_BASE=/opt/oracle
ENV ORACLE_HOME=${ORACLE_BASE}/instantclient_23_7
ENV PATH=$ORACLE_HOME:$PATH
ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$ORACLE_HOME 
ENV TNS_ADMIN=${ORACLE_HOME}/network/admin

WORKDIR /home/testhost

COPY test .

# Definir el nombre del servicio Oracle a testear
ENV LISTA_HOST=HOST:PUERTO/INSTANCIA
ENV TIEMPO_PAUSA="1"

CMD [ "sh", "test-host.sh"]