FROM ubuntu:22.04
ENV LD_LIBRARY_PATH=/opt/oracle/instantclient_23_7:$LD_LIBRARY_PATH
ENV PATH=/opt/oracle/instantclient_23_7:$PATH
RUN apt update -y && \
    apt upgrade -y && \
    apt install -y curl \
    libaio1 \
    unzip
RUN mkdir -p /opt/oracle
WORKDIR /opt/oracle
RUN curl -o oracleclient.zip https://download.oracle.com/otn_software/linux/instantclient/2370000/instantclient-basic-linux.x64-23.7.0.25.01.zip && \
    curl -o sqlplus.zip https://download.oracle.com/otn_software/linux/instantclient/2370000/instantclient-sqlplus-linux.x64-23.7.0.25.01.zip && \
    curl -o oracletools.zip https://download.oracle.com/otn_software/linux/instantclient/2370000/instantclient-tools-linux.x64-23.7.0.25.01.zip && \    
    unzip oracleclient.zip && \
    unzip -n oracletools.zip && \
    unzip -n sqlplus.zip && \
    sh -c "echo /opt/oracle/instantclient_23_7 > \
    /etc/ld.so.conf.d/oracle-instantclient.conf" && \
    ldconfig

CMD [ "tail", "-f", "/dev/null"]