FROM debian:stable-slim

#se debe instalar libaio1, en otros sistemas operativos es libaio nada mas
RUN apt update -y && \
    apt install -y \
    unzip \
    libaio1 \
    curl

WORKDIR /opt/oracle

RUN curl -o oracleclientlite.zip https://download.oracle.com/otn_software/linux/instantclient/2370000/instantclient-basiclite-linux.x64-23.7.0.25.01.zip && \
    unzip oracleclientlite.zip && \
    sh -c "echo /opt/oracle/instantclient_23_7 > \
    /etc/ld.so.conf.d/oracle-instantclient.conf" && \
    ldconfig && \
    rm oracleclientlite.zip

RUN apt remove --purge -y \
    unzip \
    curl
    
WORKDIR /opt/oracle/instantclient_23_7

COPY oracle/instantclient_23_7/network ./network
COPY oracle/instantclient_23_7/tnsping ./tnsping

ENV ORACLE_BASE=/opt/oracle
ENV ORACLE_HOME=${ORACLE_BASE}/instantclient_23_7
ENV PATH=$ORACLE_HOME:$PATH
ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$ORACLE_HOME 
ENV TNS_ADMIN=${ORACLE_HOME}/network/admin

WORKDIR /home/proceso

COPY proceso .

# Definir el nombre del servicio Oracle a testear
ENV LISTA_HOST=HOST:PUERTO/INSTANCIA
ENV TIEMPO_PAUSA="1"

CMD [ "sh", "test-host.sh"]